logging:
  level:
    com.soundwave: INFO
    org.springframework.web: INFO

seq:
  gelf:
    host: ${SEQ_GELF_HOST:localhost}

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/soundwave
    username: soundwave
    password: soundwave
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
