import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate } from 'k6/metrics';
import { randomString, randomIntBetween, uuidv4 } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080/api/v1';

const businessErrors = new Rate('business_errors');

export const options = {
    scenarios: {
        happy_path: {
            executor: 'ramping-vus',
            exec: 'happyPath',
            startVUs: 0,
            stages: [
                { duration: '30s', target: 10 },
                { duration: '2m', target: 25 },
                { duration: '1m', target: 40 },
                { duration: '30s', target: 0 },
            ],
            gracefulRampDown: '10s',
        },
        chaos: {
            executor: 'constant-arrival-rate',
            exec: 'chaos',
            rate: 6,
            timeUnit: '1s',
            duration: '4m',
            preAllocatedVUs: 8,
            startTime: '20s',
        },
    },
    thresholds: {
        http_req_duration: ['p(95)<800'],
        business_errors: ['rate<0.30'],
    },
};

const GENRES = ['ROCK', 'POP', 'HIP_HOP', 'JAZZ', 'CLASSICAL', 'ELECTRONIC', 'COUNTRY', 'METAL', 'FOLK'];
const JSON_HEADERS = { headers: { 'Content-Type': 'application/json' } };

function postJson(url, body) {
    return http.post(url, JSON.stringify(body), JSON_HEADERS);
}

function putJson(url, body) {
    return http.put(url, JSON.stringify(body), JSON_HEADERS);
}

function randomDigits(n) {
    let s = '';
    for (let i = 0; i < n; i++) s += Math.floor(Math.random() * 10);
    return s;
}

function randomIsrc() {
    const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    let s = '';
    for (let i = 0; i < 5; i++) s += letters[Math.floor(Math.random() * 26)];
    return s + randomDigits(7);
}

function randomGenre() {
    return GENRES[Math.floor(Math.random() * GENRES.length)];
}

export function happyPath() {
    let artistId;
    let productId;

    group('create artist', () => {
        const r = postJson(`${BASE_URL}/artists`, {
            name: `Artist ${randomString(10)}`,
            bio: 'Generated by k6 load test',
        });
        const ok = check(r, { 'artist 2xx': (x) => x.status >= 200 && x.status < 300 });
        businessErrors.add(!ok);
        if (ok) artistId = r.json('id');
    });

    if (!artistId) return;

    group('create product', () => {
        const r = postJson(`${BASE_URL}/products`, {
            title: `Album ${randomString(12)}`,
            artistId,
            upc: randomDigits(12),
            releaseDate: '2026-06-01',
            genre: randomGenre(),
            price: { amount: 9.99, currency: 'EUR' },
        });
        const ok = check(r, { 'product 201': (x) => x.status === 201 });
        businessErrors.add(!ok);
        if (ok) productId = r.json('id');
    });

    if (!productId) return;

    group('add tracks', () => {
        const count = randomIntBetween(2, 5);
        for (let i = 1; i <= count; i++) {
            const r = postJson(`${BASE_URL}/products/${productId}/tracks`, {
                title: `Track ${i} ${randomString(6)}`,
                durationMs: randomIntBetween(90000, 320000),
                trackNumber: i,
                isrc: randomIsrc(),
            });
            check(r, { 'track 2xx': (x) => x.status >= 200 && x.status < 300 });
        }
    });

    group('publish', () => {
        const r = http.post(`${BASE_URL}/products/${productId}/publish`);
        const ok = check(r, { 'publish 2xx': (x) => x.status >= 200 && x.status < 300 });
        businessErrors.add(!ok);
    });

    group('update metadata', () => {
        const r = putJson(`${BASE_URL}/products/${productId}`, {
            title: `Album ${randomString(12)} (Remastered)`,
            upc: randomDigits(12),
            releaseDate: '2026-09-01',
            genre: randomGenre(),
            price: { amount: 12.99, currency: 'EUR' },
        });
        check(r, { 'update 2xx': (x) => x.status >= 200 && x.status < 300 });
    });

    if (Math.random() < 0.4) {
        group('takedown', () => {
            const r = http.post(`${BASE_URL}/products/${productId}/takedown`);
            check(r, { 'takedown 2xx': (x) => x.status >= 200 && x.status < 300 });
        });
    }

    sleep(randomIntBetween(1, 3));
}

export function chaos() {
    const roll = Math.random();

    if (roll < 0.25) {
        const r = postJson(`${BASE_URL}/products`, {
            title: 'Orphan',
            artistId: uuidv4(),
            upc: randomDigits(12),
            releaseDate: '2026-01-01',
            genre: 'ROCK',
            price: { amount: 5.0, currency: 'EUR' },
        });
        check(r, { 'missing artist rejected': (x) => x.status >= 400 && x.status < 500 });
    } else if (roll < 0.5) {
        const r = http.post(`${BASE_URL}/products/${uuidv4()}/publish`);
        check(r, { 'missing product rejected': (x) => x.status >= 400 && x.status < 500 });
    } else if (roll < 0.75) {
        const r = postJson(`${BASE_URL}/artists`, { name: '', bio: '' });
        check(r, { 'empty artist rejected': (x) => x.status === 400 });
    } else {
        const r = postJson(`${BASE_URL}/products`, {
            title: '',
            artistId: uuidv4(),
            upc: 'not-a-upc',
            releaseDate: '2026-01-01',
            genre: 'ROCK',
            price: { amount: -1, currency: 'XX' },
        });
        check(r, { 'invalid product rejected': (x) => x.status === 400 });
    }
}

export default function () {
    happyPath();
}
