@baseUrl = http://localhost:8080/api/v1
@artistId = 0f9554fc-cc87-414b-89df-907de7a157ef

### Create artist
POST {{baseUrl}}/artists
Content-Type: application/json

{
  "name": "Fleetwood Mac",
  "bio": "British-American rock band formed in London in 1967"
}

> {%
client.global.set("artistId", response.body.id);
%}

### Get artist
GET {{baseUrl}}/artists/{{artistId}}

### List artists
GET {{baseUrl}}/artists?page=0&size=20&sort=name

### Update artist
PUT {{baseUrl}}/artists/{{artistId}}
Content-Type: application/json

{
  "name": "Fleetwood Mac",
  "bio": "Updated artist bio for event and cache invalidation flow"
}
